### ISSUE TITLE
Screenshots are not visible in documentation at any page

### ISSUE THREAD

**Issue by bhardwajpriyanshu1208** [SAP-samples/btp-cap-multitenant-saas#12]
![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/68856886/9ca926b3-448b-415b-99e0-e0efa042fd90)
![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/68856886/081ff09f-0947-45ef-978e-490dcbc0ffa0)

**Comment by gregorwolf** [comment]
I don't see any issues at https://github.com/SAP-samples/btp-cap-multitenant-saas/tree/main/docu/1-discover/1-discover-tutorial-target:

<img width="1275" alt="Screenshot 2023-12-28 at 09 47 38" src="https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/2639535/6a0fd03c-2d64-4d6e-a3cc-59d0f1ada23f">

Please check your browser settings.
