### ISSUE TITLE
Update npm package versions in the repo

### ISSUE THREAD

**Issue by alperdedeoglu** [SAP-samples/btp-cap-multitenant-saas#14]
npm dependency versions must be updated and repo should be tested afterwards functionalitywise.

Following packages have the prio: 
- @sap/cds
- @sap/cds-mtxs

**Comment by AjitKP91** [comment]
@alperdedeoglu Will update the versions and test basic version (locally and deployed on cf Kyma)

**Comment by alperdedeoglu** [comment]
@AjitKP91 linked branch fixed the issues we have faced during the upgrade of the versions. You might remove yours.
