### ISSUE TITLE
shared db not used

### ISSUE THREAD

**Issue by maxi1555** [SAP-samples/btp-cap-multitenant-saas#19]
I believe that there is not usage of the shared db, it would be great to add examples to read / write data from any ui app with the corresponding service.

DB Content: https://github.com/SAP-samples/btp-cap-multitenant-saas/tree/main/code/db-com

Kind Regards.
Max.

**Comment by alperdedeoglu** [comment]
Hi Maxi,
Checked the repo and you are right. There should be one example where the usage needs to be shown.

Will add it and update here. 
Best,
Alper

**Comment by maxi1555** [comment]
If you need an example, you can implement a feedback service where the users provide rating and a text, and the admin can read them :)

**Comment by alperdedeoglu** [comment]
Example has been provided,
Shared Entity currently is using the Common HDI Container, with CRUD operations.
