### ISSUE TITLE
When trying to build on widnows

### ISSUE THREAD

**Issue by laberge1234** [SAP-samples/btp-cap-multitenant-saas#35]
There is an error when trying to build from windows only for api & srv images using main branch

![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/22175716/16cdf2c1-19a3-4c1a-b714-58ad35ff9623)

**Comment by AjitKP91** [comment]
Hi @laberge1234,

Could you please provide a bit more info.?
- Are you trying to build only srv and api? 
- Can you tell us the command you are using to build?
- Is docker running on your system? and what is the version?
- could you also provide your npm and cds version?

Regards, Ajit

**Comment by laberge1234** [comment]
Yes it is all running !

    "build:srv": "cross-env-shell pack build $IMAGE_PREFIX/susaas-srv --path ../../code/gen/srv --builder paketobuildpacks/builder:base --buildpack gcr.io/paketo-buildpacks/nodejs -e BP_LAUNCHPOINT=./node_modules/@sap/cds/bin/cds-serve.js",
    "build:api": "cross-env-shell pack build $IMAGE_PREFIX/susaas-api --path ../../code/gen/api --builder paketobuildpacks/builder:base --buildpack gcr.io/paketo-buildpacks/nodejs -e BP_LAUNCHPOINT=./node_modules/@sap/cds/bin/cds-serve.js",

I run : npm run build:srv and npm run build:api
The other image are building fine
The issue is happening inside the container while building, on my computer. I can run it localy it builds fine. there is a difference between the npm local commands and the build flow with the pack command.

**Comment by AjitKP91** [comment]
@laberge1234  Thanks for providing detaills.

**Comment by AjitKP91** [comment]
@laberge1234  

I think you are missing some installations like paketo or helm etc on your local machine  Can you make sure you have all the required installations (especially paketo, helm, docker)  as provided in following tutorial: https://developers.sap.com/tutorials/btp-app-kyma-prepare-dev-environment.html

**Comment by laberge1234** [comment]
No I was able to build this one : build:db-com
It uses all the dependencies on your link.
This builder : --builder paketobuildpacks/builder:base does not work with the project.

**Comment by alperdedeoglu** [comment]
Can you try `paketobuildpacks/builder-jammy-base` builder?

**Comment by laberge1234** [comment]
Yes I also tried this image ! Deleting node _module and packacge.lock

**Comment by alperdedeoglu** [comment]
I do not currently have a windows machine, we need to check this with a colleague who has it.

Will update here.

**Comment by thomaslaberge** [comment]
Thank you your last commit allowed me to build. I probably forgot to delete a package.lock in a directory somewhere. This was the root cause of the problem.

**Comment by alperdedeoglu** [comment]
Great to hear, thank you for adopting the repo and keep us updated if you find any other issues. We appreciate any type of contribution!
