### ISSUE TITLE
Subscription failed: “Please contact the owner of application/service vendortracker with appName: vendortracker -myOrg. It failed its asynchronous callback and responded with message: Tenant creation failed.“

### ISSUE THREAD

**Issue by SyedBabaTajuddinHussaini** [SAP-samples/btp-cap-multitenant-saas#42]
* Issue Description: I am encountering an issue while attempting to subscribe to an SAP CAP Multitenant application deployed within the SAP BTP Cloud Foundry Environment. Below is a detailed description of the problem:

* Summary: I have successfully developed and deployed an SAP CAP Multitenant application within the SAP BTP environment. However, when attempting to subscribe to this application from another subaccount (consumer subaccount within same global account), I encountered a subscription failure. 

* Detail Description: I have developed and deployed an SAP CAP Multitenant application to the SAP BTP Cloud Foundry Environment. Upon attempting to subscribe to the SAP CAP Multitenant application, I encountered the following error message within the SAP BTP Subscription Management Dashboard: "Please contact the owner of the application/service 'vendortracker' with appName: 'vendortracker-myOrg'. It failed its asynchronous callback and responded with the message: 'Tenant creation failed.'"

* SAP BTP Subscription Management Dashboard: Screenshots: I have attached screenshots below for your review.

![1](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/37118657/a6708ef6-8346-4071-b076-2a300418c2d7)
![2](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/37118657/beb87364-c84b-45e6-a013-7d57907c42db)
![3](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/37118657/fd25738e-7eb5-4d19-bf0d-9426062d94d3)

Looking forward to receiving assistance from the experts.

Regards,
Syed

**Comment by alperdedeoglu** [comment]
Can you share the response from network?

**Comment by SyedBabaTajuddinHussaini** [comment]
![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/37118657/d9dff044-c75d-4bec-aded-da652a3c3e1e)

**Comment by SyedBabaTajuddinHussaini** [comment]
{
        "name": "vendortracker-myOrg",
        "title": "vendortracker",
        "description": "Vendor Tracker Application by Taj",
        "shortDescription": "Vendor Tracker Application by Taj",
        "type": "APPLICATION",
        "license": "FREE",
        "state": "SUBSCRIBE_FAILED",
        "isAccountLicensed": true,
        "url": "",
        "applicationId": "vendortracker-myOrg!t0012",
        "applicationCoordinates": {
            "serviceCategories": [
                {
                    "name": "Category"
                }
            ]
        },
        "createdDate": "1718200944323",
        "modifiedDate": "1718200948161",
        "stateDetails": {
            "message": "Please contact the owner of application/service vendortracker with appName: vendortracker-myOrg. It failed its asynchronous callback and responded with message: Tenant creation failed."
        },
        "authenticationProvider": "XSUAA",
        "supportsParametersUpdates": false,
        "supportsPlanUpdates": false
    },

**Comment by alperdedeoglu** [comment]
do you see any logs on the susaas-srv application after subscription? Is request reaching to the application?

**Comment by alperdedeoglu** [comment]
Do you have a separate application for mtx?

**Comment by SyedBabaTajuddinHussaini** [comment]
![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/37118657/d9e2dc0b-5975-442e-8b62-7a36edc3f1a2)

**Comment by SyedBabaTajuddinHussaini** [comment]
Thank you so much.
I will try to follow the steps as you have mentioned above.

**Comment by SyedBabaTajuddinHussaini** [comment]
Hi @alperdedeoglu,

As suggested by you I tried to create a new project from scratch by using these commands: 

cds init vendor-tracker --add nodejs,mta,mtx,hana,tiny-sample
cd vendor-tracker
npm install
mbt build

after mbt build I am getting the following error:
![image](https://github.com/SAP-samples/btp-cap-multitenant-saas/assets/37118657/65019b9c-7107-446c-bbfe-5c22b6fc3f7d)

Request you to kindly guide me how to fix this error.

Regards,
Syed
