### ISSUE TITLE
Documentation: definition of Consumer/Tenant Subaccount

### ISSUE THREAD

**Issue by sapaware** [SAP-samples/btp-cap-multitenant-saas#43]
On [this](https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/docu/1-discover/5-understand-btp-multitenancy/README.md) documentation page, 'Consumer/Tenant Subaccount' is defined as: 

"Consumer/Tenant Subaccount A Consumer or Tenant is the user of the SaaS application. This can be another team or company that is going to use the multitenant SaaS solution. This Consumer subscribes to the SaaS solution from their Consumer Subaccount which is a subaccount of the **vendor's** Global Account in SAP BTP."

I think Consumer's subaccount is a subaccount of **consumer's** Global Account and not vendor's.

**Comment by gregorwolf** [comment]
Hi @sapaware,

unfortunately a subscription from a subaccount that is part of the consumers Gloabl Account isn't possible (if you're not SAP).

**Comment by sapaware** [comment]
Oh, I see. I get it now. Consumer's can only subscribe to SAP provided SaaS application from their own Global Account. But, for vendor provided SaaS applications, it's the vendor who has to do the onboarding for the consumer. 
I hope I understand it correctly.

**Comment by alperdedeoglu** [comment]
Hi @sapaware, 
As @gregorwolf mentioned, for partner and customer solutions, it is not possible to do a cross global account subscription.
Therefore the SaaS solution and the consumer subaccount is in the same global account. And this global account belongs to SaaS vendor.

For SAP Internal SaaS products, what you stated is correct, but this is not possible for partner or customer developed solutions. That is why we precisely defined what a consumer subaccount means in this context.
