### ISSUE TITLE
Deprecating Self Onboarding

### ISSUE THREAD

**Issue by alperdedeoglu** [SAP-samples/btp-cap-multitenant-saas#57]

**Comment by alperdedeoglu** [comment]
Self onboarding portion of the repo must be deprecated.

**Comment by gregorwolf** [comment]
Is something better planned?

**Comment by alperdedeoglu** [comment]
No, but adoption of that part in the repo is low. We have never heard anyone actually tried it. I would personally like to invest other topics might be more attractive for our SaaS community here.

**Comment by gregorwolf** [comment]
But I think the missing adoption is more a commercial than a technical problem. Because as I understood you can only get the productive resouces provisioned when you have the first subscriber.
