### ISSUE TITLE
How  to implement  multitenacy in CAP projetc with custiomized app

### ISSUE THREAD

**Issue by Deepanshu2906** [SAP-samples/btp-cap-multitenant-saas#61]
I have implemented a project with a basic folder structure of my App  as attached,   I was trying to implememnt  from your repo. But having issue that , what are the mandatory files that  I must include in srv folder  of my custom project .
![Screenshot 2024-09-18 094752](https://github.com/user-attachments/assets/bb61e48d-ee39-442e-96d5-17de068094cd)
your srv folder have below structure : 
![image](https://github.com/user-attachments/assets/857d8ec4-337b-49d3-97de-b2c9f0a8df97)

I  am having  confusion in configuring  server module  in mta.yaml.As you have defined API folder ,having backend services to be consumed. I my case I have srv folder where backend service are generally defined and you can see many custom fiori apps that are consuming services from my srv folder.So how to approach in that case ?

Is it mandatory to have first screen like below for User managemment Dashboard ?  :
![image](https://github.com/user-attachments/assets/8ba199e4-8516-4794-9af6-6931c51a0076)
After above screen my fiori app should appear as per member and user defined.

**Comment by alperdedeoglu** [comment]
That is the same in our case. 
In our repository, there are also more than one UI application consuming backend services. Of course it is not mandatory to have a mock launchpad. That is the design decision we took, to be able to show the available UI apps in an easy fashion. It is not mandatory. But as you see in the repo we also have more than one UI application and that works.

Services under **/api** are not consumed by UI applications, only the services under **/srv** are consumed by UI applications.

> Is it mandatory to have first screen like below for User managemment Dashboard ? 

No it is not.

> After above screen my fiori app should appear as per member and user defined.

This I did not understand.

**Comment by Deepanshu2906** [comment]
Thanks👍 for clearing  .
It means / api folder code can be put inside /srv also ?
Please clear some  points:
1) Under /srv directory there are many files and  in Utils folder  also many file. show below 👍 
![image](https://github.com/user-attachments/assets/52b0fe0d-5433-4046-b8d9-3b0ecbe62bdb)
so  can you mention which are bare min mandatory files that is required for my custom projects. 

Can I exclude autoscaler and credentials store ? 
I am having  problem in configuring mta file. as I am exploring BTP having 1 year of experince.
Could you connect if available .

**Comment by alperdedeoglu** [comment]
Autoscaler you can exclude, credentials store in our case needed to connect CF API's to create routes.
I would strongly suggest you to go through our documentation to understand which component does what. They are described.
