### ISSUE TITLE
Tenant URl not reachable

### ISSUE THREAD

**Issue by gekko68** [SAP-samples/btp-cap-multitenant-saas#78]
Hi, after a succesfull deployment and subscription of the app : I am getting an error message :

404 Not Found: Requested route ('430309b6trial-susaas-dev.cfapps.us10-001.hana.ondemand.com') does not exist.

In the subscription dashboard I can see the subscription 

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/2eb104f9-42fb-4e08-bbd2-3a26d3cc06ad">

Any idea what to check ?

**Comment by alperdedeoglu** [comment]
Hello @gekko68,
Welcome to the our SaaS community!
Can you make sure if the username and password in your credential store is correct?

After that can you try subscribing from a fresh subaccount?

**Comment by gekko68** [comment]
> Hello @gekko68, Welcome to the our SaaS community! Can you make sure if the username and password in your credential store is correct?
> 
> After that can you try subscribing from a fresh subaccount?

Good morning [alperdedeoglu](https://github.com/alperdedeoglu),
made it working but not sure if that was intentionally ... I have set the routes in CF manually for the two tenants after the subscription and now the routes are accessible. Shouldn't that been done automatically during the subscription ?

<img width="1694" alt="image" src="https://github.com/user-attachments/assets/32679624-804e-480b-ae37-7e1e6c073f2b">

**Comment by alperdedeoglu** [comment]
> > Hello @gekko68, Welcome to the our SaaS community! Can you make sure if the username and password in your credential store is correct?
> > After that can you try subscribing from a fresh subaccount?
> 
> Good morning @alperdedeoglu , made it working but not sure if that was intentionally ... I have set the routes in CF manually for the two tenants after the subscription and now the routes are accessible. Shouldn't that been done automatically during the subscription ?
> 
> <img alt="image" width="1694" src="https://private-user-images.githubusercontent.com/7279399/384670986-32679624-804e-480b-ae37-7e1e6c073f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAyODQsIm5iZiI6MTczMTIyOTk4NCwicGF0aCI6Ii83Mjc5Mzk5LzM4NDY3MDk4Ni0zMjY3OTYyNC04MDRlLTQ4MGItYWUzNy03ZTFlNmMwNzNmMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMDkxMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM1Y2QwZTJjOWJhMWRhZjc2MDM2OWVhZDMyN2NmNzZkNmM0NGRhYWE5NGY5YjNjMzM1ZDgwMTA3OTJhMWY3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1d_YRl4oB7cGC3z6WvMdtw4X_-baQuHkR3HPXP2DmDc">

Indeed, that routes also should be created automatically.
To be able to do that in CF, we need to interact with CF Routes API which requires a user who is an org member and space developer.
That is why I asked you to check your username and password. 

You can of course manually create the routes, it would work.

I would still recommend you to check your username and password in credential store and try again with a fresh consumer subaccount.

**Comment by gekko68** [comment]
@alperdedeoglu 

mmh. I am the only user on the BTP Trial and have all roles etc assigened ...

When u mention the credential store u mean the one of : dev-susaas-credstore - Credential Store, correct ?
If yes, did I miss to set something in the deplyment files ?

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/4028f279-21e9-4eba-ba39-7d68d647390f">

I have an entry under referencing apps

**Comment by alperdedeoglu** [comment]
Yes, but I think I know what is going wrong in your case. 
Can you please recheck if you have done [this step](https://github.com/SAP-samples/btp-cap-multitenant-saas/tree/main/docu/2-basic/3-cf-build-deploy-application#2-setup-the-credential-store)? 

If you entirely skipped the section, please unsubscribe all the tenants do the steps, and deploy again.

Credential store part is crucial for CF deployment. Automation of route creation, service broker registration would not work without that.

**Comment by gekko68** [comment]
> Yes, but I think I know what is going wrong in your case. Can you please recheck if you have done [this step](https://github.com/SAP-samples/btp-cap-multitenant-saas/tree/main/docu/2-basic/3-cf-build-deploy-application#2-setup-the-credential-store)?
> 
> If you entirely skipped the section, please unsubscribe all the tenants do the steps, and deploy again.
> 
> Credential store part is crucial for CF deployment. Automation of route creation, service broker registration would not work without that.

@alperdedeoglu I just check everything and created the Credential Store. U were right. looks like i somehow skipped it. It is perfectly working now .

Thank you !!!!

**Comment by gekko68** [comment]
Working as designed.

**Comment by alperdedeoglu** [comment]
> Working as designed.

Happy to hear that, cheers!
